### ISSUE TITLE
Contribute to awesome neovim

### ISSUE THREAD

**Issue by bellini666** [mg979/tabline.nvim#1]
Hey,

Nice work! Just saw that you created a new plugin based on xtabline using lua.

You should contribute it to the https://github.com/rockerBOO/awesome-neovim list! Maybe add some images, etc before as people might now know how this looks. I know because I'm an old user from the previous plugin =P

**Comment by mg979** [comment]
Thanks but that list is pretty crowded already and I'm just not a crowd guy. Anyway, if you have suggestions on how to improve the plugin, they're welcome.

**Comment by bellini666** [comment]
@mg979 oh I see. Np! :)

It's just that yours is the only lua-based tabline that I know of that can work with tabs only. But I get that you are not a crowd guy :)

Anyway, will come here to post any suggestions/issues if I have/find any.

**Comment by mg979** [comment]
Yes, I like a lot barbar.nvim looks but I prefer tabs, that's why I rewrote xtabline here :).
