### ISSUE TITLE
Can I define highlights groups by myself?

### ISSUE THREAD

**Issue by ofseed** [mg979/tabline.nvim#17]
It seems that I could not define these highlights directly, because tabline will override them once it is loaded. The reason is some themes provide a convenient API to define the colors between variants they provide.

For catppuccin:
```lua
custom_highlights = function(color)
  return {
    TFill = { fg = color.subtext0, bg = color.mantle },
    TSel = { fg = color.base, bg = color.overlay1 },
  }
end,

```

Then the highlights will be available for the four variants it provides.

**Comment by mg979** [comment]
:help TablineThemePost

**Comment by ofseed** [comment]
Thanks a lot.
