### ISSUE TITLE
Best tabline plugin ever

### ISSUE THREAD

**Issue by rockyzhang24** [mg979/tabline.nvim#7]
Coming here from vim-xtabline that I have been using for three years. After trying all the tabline/bufferline plugins, unequivocally I can say vim-xtabline (and tabline.nvim) is the best. Definitely! It has all the features a tabline should have. Simple but powerful. 

I just want to say thanks here. Thank you for your continued active maintenance ♥️

**Comment by mg979** [comment]
Thanks a lot! I recently reimplemented persistance in sessions (missing feature from xtabline) so now they're on feature parity, more or less. Thanks again for the appreciation!

**Comment by rockyzhang24** [comment]
Added this plugin to [awesome neovim](https://github.com/rockerBOO/awesome-neovim) 😁
