### ISSUE TITLE
Customized mapping does not work

### ISSUE THREAD

**Issue by rockyzhang24** [mg979/tabline.nvim#8]
I tried to map changing tabline mode to a key 

```lua
local L = settings.mapleader

local mappping = {
  ['mode buffers'] = L .. 'mb',
  ['mode tabs'] = L .. 'mt',
  ['mode args'] = L .. 'ma',
  ['mode next'] = L .. mn',
}

tabline.mappings(mappings)
```

However, only `mode next` works well, and the other three doesn't work. Now, instead I have to use the cmdline commands to define my own mappings, e.g., `nnoremap <leader>mb <Cmd>Tabline mode buffers`. 

Thank you.

**Comment by mg979** [comment]
Should be fixed, please reopen if it's not.
